export const runeDescriptions = [
  {
    description: 'Improved attacks and sustained damage.',
    key: 'Precision',
  },
  {
    description: 'Burst damage and target access.',
    key: 'Domination',
  },
  {
    description: 'Empowered abilities and resource manipulation.',
    key: 'Sorcery',
  },
  {
    description: 'Durability and crowd control',
    key: 'Resolve',
  },
  {
    description: 'Creative tools and rule bending',
    key: 'Inspiration',
  },
]

export const regions = [
  'NA1',
  'BR1',
  'EUN1',
  'EUW1',
  'JP1',
  'KR',
  'LA1',
  'LA2',
  'OC1',
  'RU',
  'TR1',
]

export const laneChamp = {
  Top: {
    s: [
      'Darius',
      'Shen',
      'Pantheon',
      'Lulu',
      'Malphite',
      'Wukong',
      'Garen',
      'Nasus',
      "Cho'Gath",
      'Sion',
      'Karma',
      'Soraka',
    ],
    a: [
      'Camille',
      'Ornn',
      'Kled',
      'Fiora',
      'Urgot',
      'Kayle',
      'Sett',
      'Poppy',
      'Volibear',
      'Maokai',
      'Jax',
      'Quinn',
      'Teemo',
    ],
    b: [
      'Rengar',
      'Gnar',
      'Riven',
      'Akali',
      'Aatrox',
      'Singed',
      'Renekton',
      'Illaoi',
      'Mordekaiser',
      'Kennen',
      'Yorick',
      'Tryndamere',
    ],
  },
  Mid: {
    s: [
      'Viktor',
      'Ekko',
      'Anivia',
      'Galio',
      'Fizz',
      'Seraphine',
      'Pantheon',
      'Annie',
      'Malzahar',
    ],
    a: [
      'Zed',
      'Yasuo',
      'Yone',
      "Vel'Koz",
      'Orianna',
      'Ahri',
      'Kayle',
      'Swain',
      'Brand',
      'Morgana',
      'Neeko',
      'Lux',
      'Diana',
      'Ziggs',
      'Malphite',
    ],
    b: [
      'LeBlanc',
      'Sylas',
      'Zoe',
      'Pyke',
      'Katarina',
      'Akali',
      'Azir',
      'Cassiopeia',
      'Xerath',
      'Vladimir',
      'Twisted Fate',
      'Talon',
      'Syndra',
      'Kassadin',
      'Veigar',
      'Lissandra',
    ],
  },
  Adc: {
    s: ['Vayne', "Kai'Sa", 'Swain', 'Jhin', 'Ashe', 'Miss Fortune', 'Tristana'],
    a: [
      'Samira',
      'Lucian',
      'Viktor',
      'Seraphine',
      'Caitlyn',
      'Heimerdinger',
      'Senna',
      "Kog'Maw",
      'Twitch',
      'Jinx',
      'Sivir',
    ],
    b: [
      'Aphelios',
      'Kalista',
      'Ezreal',
      'Yasuo',
      'Draven',
      'Varus',
      'Xayah',
      'Ziggs',
    ],
  },
  Support: {
    s: [
      'Thresh',
      'Seraphine',
      'Zilean',
      'Lulu',
      'Alistar',
      'Leona',
      'Janna',
      'Soraka',
    ],
    a: [
      'Bard',
      'Rell',
      'Galio',
      'Pantheon',
      'Swain',
      'Nami',
      'Maokai',
      'Karma',
      'Lux',
      'Morgana',
      'Yuumi',
      'Nautilus',
      'Blitzcrank',
      'Sona',
      'Brand',
      'Zyra',
    ],
    b: [
      'Pyke',
      "Vel'Koz",
      'Rakan',
      'Shaco',
      'Xerath',
      'Shen',
      'Senna',
      'Braum',
      'Taric',
      'Annie',
    ],
  },
  Jungle: {
    s: [
      "Kha'Zix",
      'Ivern',
      'Udyr',
      'Skarner',
      'Rammus',
      'Olaf',
      'Nunu & Willump',
      'Hecarim',
      'Elise',
    ],
    a: [
      'Evelynn',
      'Taliyah',
      'Ekko',
      'Poppy',
      'Graves',
      'Fiddlesticks',
      'Kayn',
      'Amumu',
      'Warwick',
      'Volibear',
      'Master Yi',
      'Dr. Mundo',
      'Sejuani',
      'Vi',
    ],
    b: [
      'Lee Sin',
      'Nidalee',
      "Rek'Sai",
      'Shaco',
      'Lillia',
      'Gragas',
      'Zac',
      'Shyvana',
      'Xin Zhao',
      'Jarvan IV',
      'Jax',
      'Nocturne',
      'Trundle',
    ],
  },
}
