export const runeDescriptions = [
  {
    description: "Improved attacks and sustained damage.",
    key: "Precision",
  },
  {
    description: "Burst damage and target access.",
    key: "Domination",
  },
  {
    description: "Empowered abilities and resource manipulation.",
    key: "Sorcery",
  },
  {
    description: "Durability and crowd control",
    key: "Resolve",
  },
  {
    description: "Creative tools and rule bending",
    key: "Inspiration",
  },
];

export const backupItem = {
  3147: {
    name: "Duskblade of Draktharr",
    description:
      "<stats>+60 Attack Damage<br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive</unique>: +21 <a href='Lethality'>Lethality</a><br><unique>UNIQUE Passive - Nightstalker:</unique> After being unseen for at least 1 second, your next basic attack against an enemy champion deals <scaleLevel>30 - 150</scaleLevel> bonus physical damage and slows them by 99% for 0.25 seconds. Ranged basic attacks do not apply the slow. (Lasts for 5 seconds after being seen by an enemy champion).",
    colloq: ";lethality",
    plaintext: "Deals additional physical damage when ambushing enemies",
    from: ["3134", "3133"],
    image: {
      full: "3147.png",
      sprite: "item1.png",
      group: "item",
      x: 240,
      y: 192,
      w: 48,
      h: 48,
    },
    gold: {
      base: 700,
      purchasable: true,
      total: 2900,
      sell: 2030,
    },
    tags: ["Damage", "CooldownReduction", "OnHit", "ArmorPenetration"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 60,
    },
    effect: {
      Effect1Amount: "21",
      Effect2Amount: "0",
      Effect3Amount: "0",
      Effect4Amount: "0",
      Effect5Amount: "30",
      Effect6Amount: "150",
      Effect7Amount: "99",
      Effect8Amount: "0.25",
      Effect9Amount: "5",
      Effect10Amount: "30",
      Effect11Amount: "1",
      Effect12Amount: "150",
    },
    depth: 3,
  },
  1041: {
    name: "Hunter's Machete",
    description:
      "<stats>+10% Life Steal vs. Monsters</stats><br><br><unique>UNIQUE Passive - Nail:</unique> Basic attacks vs. Monsters deal 35 bonus damage on hit. This item grants <font color='#99BBBB'><a href='SpecialJungleExperience'>Monster Hunter</a></font>. This item's healing will be increased by 50% when under 30% Health.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";jungle;Jungle",
    plaintext: "Provides damage and life steal versus Monsters",
    into: ["3706", "3715"],
    image: {
      full: "1041.png",
      sprite: "item0.png",
      group: "item",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 350,
      purchasable: true,
      total: 350,
      sell: 245,
    },
    tags: ["LifeSteal", "OnHit", "Jungle"],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "35",
      Effect2Amount: "0.1",
      Effect3Amount: "0.3",
      Effect4Amount: "0.5",
    },
  },
  3706: {
    name: "Stalker's Blade",
    description:
      "<groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit><br><br>+10% Life Steal vs. Monsters<br><br><unique>UNIQUE Passive - Chilling Smite:</unique> Smite can be cast on enemy champions, dealing reduced true damage and stealing 20% Movement Speed for 2 seconds.<br><unique>UNIQUE Passive - Tooth / Nail:</unique> Basic attacks vs. monsters deal 40 bonus damage.  Damaging a monster with a spell or attack steals 30 Health over 5 seconds and burns them for 80 magic damage.<mana> While in the jungle or river, regenerate up to 8 Mana per second based on your missing Mana.</mana> This item grants <font color='#99BBBB'><a href='SpecialJungleExperience'>Monster Hunter</a></font>. This item's healing will be increased by 50% when under 30% Health.",
    colloq: ";jungle;Jungle;jangle",
    plaintext: "Lets your Smite slow Champions",
    from: ["1039", "1041"],
    into: ["1401", "1400", "1402", "1416"],
    image: {
      full: "3706.png",
      sprite: "item2.png",
      group: "item",
      x: 48,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 300,
      purchasable: true,
      total: 1000,
      sell: 700,
    },
    tags: [
      "LifeSteal",
      "ManaRegen",
      "Slow",
      "OnHit",
      "NonbootsMovement",
      "Jungle",
    ],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 2,
  },
  1400: {
    name: "Enchantment: Warrior",
    description:
      "<stats>+60 Attack Damage<br>+10% Cooldown Reduction</stats><br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Attack Damage and Cooldown Reduction",
    from: ["3133", "3706"],
    hideFromAll: true,
    image: {
      full: "1400.png",
      sprite: "item0.png",
      group: "item",
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 525,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 60,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1401: {
    name: "Enchantment: Cinderhulk",
    description:
      "<stats>+300 Health<br>+15% Bonus Health</stats><br><br><unique>UNIQUE Passive - Immolate:</unique> While in combat, burns nearby enemies for <scaleLevel>[12 to 29]</scaleLevel> magic damage a second. Once every 12 seconds, your next immobilizing spell deals <scaleLevel>[12 to 29]</scaleLevel> <scaleHealth>(+3% Your Bonus HP)</scaleHealth> bonus magic damage and releases a fire nova that also deals that bonus damage around you. Immolate's damage is increased by 300% damage to minions and monsters.<br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Health and Immolate Aura",
    from: ["3751", "3706"],
    hideFromAll: true,
    image: {
      full: "1401.png",
      sprite: "item0.png",
      group: "item",
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 600,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 300,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1402: {
    name: "Enchantment: Runic Echoes",
    description:
      "<stats>+80 Ability Power<br>+10% Cooldown Reduction<br><mana>+300 Mana</mana></stats><br><br><unique>UNIQUE Passive - Echo:</unique> Gain charges upon moving or casting. At 100 charges, the next damaging spell hit expends all charges to deal 60 (+10% of Ability Power) bonus magic damage to up to 4 targets on hit.<br><br>This effect deals 250% damage to Large Monsters. Hitting a Large Monster with this effect will restore 25% of your missing Mana.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Ability Power and periodically empowers your Spells",
    from: ["3108", "1027", "3706"],
    hideFromAll: true,
    image: {
      full: "1402.png",
      sprite: "item0.png",
      group: "item",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 250,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatMPPoolMod: 300,
      FlatMagicDamageMod: 80,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1412: {
    name: "Enchantment: Warrior",
    description:
      "<stats>+60 Attack Damage<br>+10% Cooldown Reduction</stats><br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Attack Damage and Cooldown Reduction",
    from: ["3133", "3715"],
    hideFromAll: true,
    image: {
      full: "1412.png",
      sprite: "item0.png",
      group: "item",
      x: 0,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 525,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 60,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1413: {
    name: "Enchantment: Cinderhulk",
    description:
      "<stats>+300 Health<br>+15% Bonus Health</stats><br><br><unique>UNIQUE Passive - Immolate:</unique> While in combat, burns nearby enemies for <scaleLevel>[12 to 29]</scaleLevel> magic damage a second. Once every 12 seconds, your next immobilizing spell deals <scaleLevel>[12 to 29]</scaleLevel> <scaleHealth>(+3% Your Bonus HP)</scaleHealth> bonus magic damage and releases a fire nova that also deals that bonus damage around you. Immolate's damage is increased by 300% damage to minions and monsters.<br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Health and Immolate Aura",
    from: ["3751", "3715"],
    hideFromAll: true,
    image: {
      full: "1413.png",
      sprite: "item0.png",
      group: "item",
      x: 48,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 600,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 300,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.4",
    },
    depth: 3,
  },
  1414: {
    name: "Enchantment: Runic Echoes",
    description:
      "<stats>+80 Ability Power<br>+10% Cooldown Reduction<br><mana>+300 Mana</mana></stats><br><br><unique>UNIQUE Passive - Echo:</unique> Gain charges upon moving or casting. At 100 charges, the next damaging spell hit expends all charges to deal 60 (+10% of Ability Power) bonus magic damage to up to 4 targets on hit.<br><br>This effect deals 250% damage to Large Monsters. Hitting a Large Monster with this effect will restore 25% of your missing Mana.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Ability Power and periodically empowers your Spells",
    from: ["3108", "1027", "3715"],
    hideFromAll: true,
    image: {
      full: "1414.png",
      sprite: "item0.png",
      group: "item",
      x: 96,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 250,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatMPPoolMod: 300,
      FlatMagicDamageMod: 80,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1416: {
    name: "Enchantment: Bloodrazor",
    description:
      "<stats>+50% Attack Speed</stats><br><br><unique>UNIQUE Passive:</unique> Basic attacks deal 4% of the target's maximum Health in bonus physical damage (max 75 vs. monsters and minions) on hit.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext:
      "Increases Attack Speed and deals damage based on the target's Health",
    from: ["1043", "3706"],
    hideFromAll: true,
    image: {
      full: "1416.png",
      sprite: "item0.png",
      group: "item",
      x: 144,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 625,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      PercentAttackSpeedMod: 0.5,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1419: {
    name: "Enchantment: Bloodrazor",
    description:
      "<stats>+50% Attack Speed</stats><br><br><unique>UNIQUE Passive:</unique> Basic attacks deal 4% of the target's maximum Health in bonus physical damage (max 75 vs. monsters and minions) on hit.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext:
      "Increases Attack Speed and deals damage based on the target's Health",
    from: ["1043", "3715"],
    hideFromAll: true,
    image: {
      full: "1419.png",
      sprite: "item0.png",
      group: "item",
      x: 192,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 625,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      PercentAttackSpeedMod: 0.5,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  3812: {
    name: "Death's Dance",
    description:
      "<stats>+50 Attack Damage<br>+30 Armor<br>+30 Magic Resist<br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive:</unique> Heal for 15% of damage dealt. This is 33% as effective for Area of Effect damage.<br><unique>UNIQUE Passive:</unique> <specialRules>[Melee Users: 30% || Ranged Users: 10%]</specialRules> of damage taken is dealt as a Bleed effect over 3 seconds instead.",
    colloq: ";Bloodbag",
    plaintext: "Trades incoming damage now for incoming damage later",
    stacks: 0,
    from: ["3105", "1053", "3133"],
    image: {
      full: "3812.png",
      sprite: "item2.png",
      group: "item",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 500,
      purchasable: true,
      total: 3600,
      sell: 2520,
    },
    tags: ["SpellBlock", "Armor", "Damage", "LifeSteal", "CooldownReduction"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 50,
      FlatSpellBlockMod: 30,
      FlatArmorMod: 30,
    },
    effect: {
      Effect1Amount: "0.15",
      Effect2Amount: "0.3",
      Effect3Amount: "3",
      Effect4Amount: "0.1",
    },
    depth: 3,
  },
  3715: {
    name: "Skirmisher's Sabre",
    description:
      "<groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit><br><br>+10% Life Steal vs. Monsters<br><br><unique>UNIQUE Passive - Challenging Smite:</unique> Smite can be cast on enemy champions, marking them for 4 seconds. While marked your basic attacks deal bonus true damage over 2.5 seconds, and their damage to you is reduced by 20%.<br><unique>UNIQUE Passive - Tooth / Nail:</unique>Basic attacks vs. monsters deal 40 bonus damage. Damaging a monster with a spell or attack steals 30 Health over 5 seconds and burns them for 80 magic damage. While in the jungle or river, regenerate up to 8 Mana per second based on your missing Mana. This item grants <font color='#99BBBB'><a href='SpecialJungleExperience'>Monster Hunter</a></font>. This item's healing will be increased by 50% when under 30% Health.",
    colloq: ";jungle;Jungle",
    plaintext:
      "Lets your Smite mark Champions, giving you combat power against them.",
    from: ["1039", "1041"],
    into: ["1412", "1413", "1414", "1419"],
    image: {
      full: "3715.png",
      sprite: "item2.png",
      group: "item",
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 300,
      purchasable: true,
      total: 1000,
      sell: 700,
    },
    tags: ["LifeSteal", "ManaRegen", "OnHit", "Jungle"],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "2.5",
      Effect8Amount: "14.5",
      Effect9Amount: "1.5",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 2,
  },
};
