export const runeDescriptions = [
  {
    description: "Improved attacks and sustained damage.",
    key: "Precision",
  },
  {
    description: "Burst damage and target access.",
    key: "Domination",
  },
  {
    description: "Empowered abilities and resource manipulation.",
    key: "Sorcery",
  },
  {
    description: "Durability and crowd control",
    key: "Resolve",
  },
  {
    description: "Creative tools and rule bending",
    key: "Inspiration",
  },
];

export const laneChamp = {
  Top: ["Teemo", "Vladimir"],
  Mid: [""],
};

export const backupItem = {
  3147: {
    version: "10.22.1",
    name: "Duskblade of Draktharr",
    description:
      "<stats>+60 Attack Damage<br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive</unique>: +21 <a href='Lethality'>Lethality</a><br><unique>UNIQUE Passive - Nightstalker:</unique> After being unseen for at least 1 second, your next basic attack against an enemy champion deals <scaleLevel>30 - 150</scaleLevel> bonus physical damage and slows them by 99% for 0.25 seconds. Ranged basic attacks do not apply the slow. (Lasts for 5 seconds after being seen by an enemy champion).",
    colloq: ";lethality",
    plaintext: "Deals additional physical damage when ambushing enemies",
    from: ["3134", "3133"],
    image: {
      full: "3147.png",
      sprite: "item1.png",
      group: "item",
      x: 240,
      y: 192,
      w: 48,
      h: 48,
    },
    gold: {
      base: 700,
      purchasable: true,
      total: 2900,
      sell: 2030,
    },
    tags: ["Damage", "CooldownReduction", "OnHit", "ArmorPenetration"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 60,
    },
    effect: {
      Effect1Amount: "21",
      Effect2Amount: "0",
      Effect3Amount: "0",
      Effect4Amount: "0",
      Effect5Amount: "30",
      Effect6Amount: "150",
      Effect7Amount: "99",
      Effect8Amount: "0.25",
      Effect9Amount: "5",
      Effect10Amount: "30",
      Effect11Amount: "1",
      Effect12Amount: "150",
    },
    depth: 3,
  },
  1041: {
    version: "10.22.1",
    name: "Hunter's Machete",
    description:
      "<stats>+10% Life Steal vs. Monsters</stats><br><br><unique>UNIQUE Passive - Nail:</unique> Basic attacks vs. Monsters deal 35 bonus damage on hit. This item grants <font color='#99BBBB'><a href='SpecialJungleExperience'>Monster Hunter</a></font>. This item's healing will be increased by 50% when under 30% Health.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";jungle;Jungle",
    plaintext: "Provides damage and life steal versus Monsters",
    into: ["3706", "3715"],
    image: {
      full: "1041.png",
      sprite: "item0.png",
      group: "item",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 350,
      purchasable: true,
      total: 350,
      sell: 245,
    },
    tags: ["LifeSteal", "OnHit", "Jungle"],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "35",
      Effect2Amount: "0.1",
      Effect3Amount: "0.3",
      Effect4Amount: "0.5",
    },
  },
  3706: {
    version: "10.22.1",
    name: "Stalker's Blade",
    description:
      "<groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit><br><br>+10% Life Steal vs. Monsters<br><br><unique>UNIQUE Passive - Chilling Smite:</unique> Smite can be cast on enemy champions, dealing reduced true damage and stealing 20% Movement Speed for 2 seconds.<br><unique>UNIQUE Passive - Tooth / Nail:</unique> Basic attacks vs. monsters deal 40 bonus damage.  Damaging a monster with a spell or attack steals 30 Health over 5 seconds and burns them for 80 magic damage.<mana> While in the jungle or river, regenerate up to 8 Mana per second based on your missing Mana.</mana> This item grants <font color='#99BBBB'><a href='SpecialJungleExperience'>Monster Hunter</a></font>. This item's healing will be increased by 50% when under 30% Health.",
    colloq: ";jungle;Jungle;jangle",
    plaintext: "Lets your Smite slow Champions",
    from: ["1039", "1041"],
    into: ["1401", "1400", "1402", "1416"],
    image: {
      full: "3706.png",
      sprite: "item2.png",
      group: "item",
      x: 48,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 300,
      purchasable: true,
      total: 1000,
      sell: 700,
    },
    tags: [
      "LifeSteal",
      "ManaRegen",
      "Slow",
      "OnHit",
      "NonbootsMovement",
      "Jungle",
    ],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 2,
  },
  1400: {
    version: "10.22.1",
    name: "Enchantment: Warrior",
    description:
      "<stats>+60 Attack Damage<br>+10% Cooldown Reduction</stats><br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Attack Damage and Cooldown Reduction",
    from: ["3133", "3706"],
    hideFromAll: true,
    image: {
      full: "1400.png",
      sprite: "item0.png",
      group: "item",
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 525,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 60,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1401: {
    version: "10.22.1",
    name: "Enchantment: Cinderhulk",
    description:
      "<stats>+300 Health<br>+15% Bonus Health</stats><br><br><unique>UNIQUE Passive - Immolate:</unique> While in combat, burns nearby enemies for <scaleLevel>[12 to 29]</scaleLevel> magic damage a second. Once every 12 seconds, your next immobilizing spell deals <scaleLevel>[12 to 29]</scaleLevel> <scaleHealth>(+3% Your Bonus HP)</scaleHealth> bonus magic damage and releases a fire nova that also deals that bonus damage around you. Immolate's damage is increased by 300% damage to minions and monsters.<br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Health and Immolate Aura",
    from: ["3751", "3706"],
    hideFromAll: true,
    image: {
      full: "1401.png",
      sprite: "item0.png",
      group: "item",
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 600,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 300,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1402: {
    version: "10.22.1",
    name: "Enchantment: Runic Echoes",
    description:
      "<stats>+80 Ability Power<br>+10% Cooldown Reduction<br><mana>+300 Mana</mana></stats><br><br><unique>UNIQUE Passive - Echo:</unique> Gain charges upon moving or casting. At 100 charges, the next damaging spell hit expends all charges to deal 60 (+10% of Ability Power) bonus magic damage to up to 4 targets on hit.<br><br>This effect deals 250% damage to Large Monsters. Hitting a Large Monster with this effect will restore 25% of your missing Mana.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Ability Power and periodically empowers your Spells",
    from: ["3108", "1027", "3706"],
    hideFromAll: true,
    image: {
      full: "1402.png",
      sprite: "item0.png",
      group: "item",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 250,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatMPPoolMod: 300,
      FlatMagicDamageMod: 80,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1412: {
    version: "10.22.1",
    name: "Enchantment: Warrior",
    description:
      "<stats>+60 Attack Damage<br>+10% Cooldown Reduction</stats><br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Attack Damage and Cooldown Reduction",
    from: ["3133", "3715"],
    hideFromAll: true,
    image: {
      full: "1412.png",
      sprite: "item0.png",
      group: "item",
      x: 0,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 525,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 60,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1413: {
    version: "10.22.1",
    name: "Enchantment: Cinderhulk",
    description:
      "<stats>+300 Health<br>+15% Bonus Health</stats><br><br><unique>UNIQUE Passive - Immolate:</unique> While in combat, burns nearby enemies for <scaleLevel>[12 to 29]</scaleLevel> magic damage a second. Once every 12 seconds, your next immobilizing spell deals <scaleLevel>[12 to 29]</scaleLevel> <scaleHealth>(+3% Your Bonus HP)</scaleHealth> bonus magic damage and releases a fire nova that also deals that bonus damage around you. Immolate's damage is increased by 300% damage to minions and monsters.<br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Health and Immolate Aura",
    from: ["3751", "3715"],
    hideFromAll: true,
    image: {
      full: "1413.png",
      sprite: "item0.png",
      group: "item",
      x: 48,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 600,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 300,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.4",
    },
    depth: 3,
  },
  1414: {
    version: "10.22.1",
    name: "Enchantment: Runic Echoes",
    description:
      "<stats>+80 Ability Power<br>+10% Cooldown Reduction<br><mana>+300 Mana</mana></stats><br><br><unique>UNIQUE Passive - Echo:</unique> Gain charges upon moving or casting. At 100 charges, the next damaging spell hit expends all charges to deal 60 (+10% of Ability Power) bonus magic damage to up to 4 targets on hit.<br><br>This effect deals 250% damage to Large Monsters. Hitting a Large Monster with this effect will restore 25% of your missing Mana.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext: "Grants Ability Power and periodically empowers your Spells",
    from: ["3108", "1027", "3715"],
    hideFromAll: true,
    image: {
      full: "1414.png",
      sprite: "item0.png",
      group: "item",
      x: 96,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 250,
      purchasable: true,
      total: 2500,
      sell: 1750,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      FlatMPPoolMod: 300,
      FlatMagicDamageMod: 80,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1416: {
    version: "10.22.1",
    name: "Enchantment: Bloodrazor",
    description:
      "<stats>+50% Attack Speed</stats><br><br><unique>UNIQUE Passive:</unique> Basic attacks deal 4% of the target's maximum Health in bonus physical damage (max 75 vs. monsters and minions) on hit.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext:
      "Increases Attack Speed and deals damage based on the target's Health",
    from: ["1043", "3706"],
    hideFromAll: true,
    image: {
      full: "1416.png",
      sprite: "item0.png",
      group: "item",
      x: 144,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 625,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      PercentAttackSpeedMod: 0.5,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "0.1",
      Effect7Amount: "2",
      Effect8Amount: "-0.2",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  1419: {
    version: "10.22.1",
    name: "Enchantment: Bloodrazor",
    description:
      "<stats>+50% Attack Speed</stats><br><br><unique>UNIQUE Passive:</unique> Basic attacks deal 4% of the target's maximum Health in bonus physical damage (max 75 vs. monsters and minions) on hit.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "",
    plaintext:
      "Increases Attack Speed and deals damage based on the target's Health",
    from: ["1043", "3715"],
    hideFromAll: true,
    image: {
      full: "1419.png",
      sprite: "item0.png",
      group: "item",
      x: 192,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 625,
      purchasable: true,
      total: 2625,
      sell: 1838,
    },
    tags: [],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {
      PercentAttackSpeedMod: 0.5,
    },
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "3",
      Effect8Amount: "18",
      Effect9Amount: "2",
      Effect10Amount: "0",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 3,
  },
  3812: {
    version: "10.22.1",
    name: "Death's Dance",
    description:
      "<stats>+50 Attack Damage<br>+30 Armor<br>+30 Magic Resist<br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive:</unique> Heal for 15% of damage dealt. This is 33% as effective for Area of Effect damage.<br><unique>UNIQUE Passive:</unique> <specialRules>[Melee Users: 30% || Ranged Users: 10%]</specialRules> of damage taken is dealt as a Bleed effect over 3 seconds instead.",
    colloq: ";Bloodbag",
    plaintext: "Trades incoming damage now for incoming damage later",
    stacks: 0,
    from: ["3105", "1053", "3133"],
    image: {
      full: "3812.png",
      sprite: "item2.png",
      group: "item",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 500,
      purchasable: true,
      total: 3600,
      sell: 2520,
    },
    tags: ["SpellBlock", "Armor", "Damage", "LifeSteal", "CooldownReduction"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 50,
      FlatSpellBlockMod: 30,
      FlatArmorMod: 30,
    },
    effect: {
      Effect1Amount: "0.15",
      Effect2Amount: "0.3",
      Effect3Amount: "3",
      Effect4Amount: "0.1",
    },
    depth: 3,
  },
  3715: {
    version: "10.22.1",
    name: "Skirmisher's Sabre",
    description:
      "<groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit><br><br>+10% Life Steal vs. Monsters<br><br><unique>UNIQUE Passive - Challenging Smite:</unique> Smite can be cast on enemy champions, marking them for 4 seconds. While marked your basic attacks deal bonus true damage over 2.5 seconds, and their damage to you is reduced by 20%.<br><unique>UNIQUE Passive - Tooth / Nail:</unique>Basic attacks vs. monsters deal 40 bonus damage. Damaging a monster with a spell or attack steals 30 Health over 5 seconds and burns them for 80 magic damage. While in the jungle or river, regenerate up to 8 Mana per second based on your missing Mana. This item grants <font color='#99BBBB'><a href='SpecialJungleExperience'>Monster Hunter</a></font>. This item's healing will be increased by 50% when under 30% Health.",
    colloq: ";jungle;Jungle",
    plaintext:
      "Lets your Smite mark Champions, giving you combat power against them.",
    from: ["1039", "1041"],
    into: ["1412", "1413", "1414", "1419"],
    image: {
      full: "3715.png",
      sprite: "item2.png",
      group: "item",
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 300,
      purchasable: true,
      total: 1000,
      sell: 700,
    },
    tags: ["LifeSteal", "ManaRegen", "OnHit", "Jungle"],
    maps: {
      11: true,
      12: false,
      21: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "80",
      Effect2Amount: "30",
      Effect3Amount: "5",
      Effect4Amount: "8",
      Effect5Amount: "40",
      Effect6Amount: "4",
      Effect7Amount: "2.5",
      Effect8Amount: "14.5",
      Effect9Amount: "1.5",
      Effect10Amount: "0.2",
      Effect11Amount: "0.1",
      Effect12Amount: "0.3",
      Effect13Amount: "0.5",
    },
    depth: 2,
  },
  3303: {
    version: "9.20.1",
    name: "Spellthief's Edge",
    description:
      "<stats>+10 Ability Power<br>+2 Gold per 10 seconds<br><mana>+25% Base Mana Regen </mana></stats><br><br><unique>UNIQUE Passive - Tribute:</unique> Damaging spells and attacks against champions or buildings deal 13 additional magic damage per unique spell cast. If there is a nearby ally Champion, it also grants <gold>11</gold> Gold. This can occur up to 3 times every 30 seconds. Before quest completion, killing minions and non-epic monsters slows Tribute and gold generation.<hr><passive>QUEST:</passive> Earn 500 gold using this item and upgrade to <font color='#CFBF84'>Frostfang</font>.<br><passive>REWARD:</passive> Gain <active>UNIQUE Active - Warding:</active> Consumes a charge to place a <font color='#BBFFFF'>Stealth Ward</font> that reveals the surrounding area for 150 seconds.  Holds up to 3 charges which refill upon visiting the shop.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";",
    plaintext: "Grants gold when you damage enemies",
    into: ["3098"],
    image: {
      full: "3303.png",
      sprite: "item2.png",
      group: "item",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
    gold: {
      base: 400,
      purchasable: true,
      total: 400,
      sell: 160,
    },
    tags: ["GoldPer", "Lane", "ManaRegen", "SpellDamage"],
    maps: {
      10: false,
      11: true,
      12: false,
      22: false,
    },
    stats: {
      FlatMagicDamageMod: 10,
    },
    effect: {
      Effect1Amount: "13",
      Effect2Amount: "11",
      Effect3Amount: "6",
      Effect4Amount: "3",
      Effect5Amount: "30",
      Effect6Amount: "2",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0",
      Effect13Amount: "0",
      Effect14Amount: "0",
      Effect15Amount: "0",
      Effect16Amount: "0",
      Effect17Amount: "500",
      Effect18Amount: "0.5",
      Effect19Amount: "1",
      Effect20Amount: "10",
    },
  },
  3304: {
    version: "9.20.1",
    name: "Timeworn Ancient Coin",
    description:
      "<stats>+5 Movement Speed<br>+5% Cooldown Reduction<br>+2 Gold per 10 seconds</stats><br><br><unique>UNIQUE Passive - Favor:</unique> Enemy minions killed by your allies sometimes drop coins that grant <scaleMana>6%</scaleMana> missing mana (minimum 10). If there is an allied Champion nearby, sometimes the coins grant <gold>28</gold> gold instead. Cannon minions always drop coins.<hr><passive>QUEST:</passive> Earn 750 gold using this item and upgrade to <font color='#CFBF84'>Timeworn Nomad's Medallion</font>.<br><passive>REWARD:</passive> <font color='#CFBF84'>Favor</font> is upgraded to <font color='#CFBF84'><a href='coinlinequestreward'>Emperor's Favor</a></font> and allied champions moving toward you gain 8% movement speed.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit><br><br><i><font color='#447777'>''Gold dust rises from the desert and clings to the coin.'' - Historian Shurelya, 11 November, 23 CLE</font></i>",
    colloq: ";",
    plaintext:
      "Grants gold and mana when nearby minions die that you didn't kill",
    into: ["3305"],
    image: {
      full: "3304.png",
      sprite: "item2.png",
      group: "item",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 400,
      purchasable: true,
      total: 400,
      sell: 160,
    },
    tags: ["ManaRegen", "GoldPer", "CooldownReduction", "Lane"],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "28",
      Effect2Amount: "10",
      Effect3Amount: "2",
      Effect4Amount: "0",
      Effect5Amount: "0",
      Effect6Amount: "0",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "0",
      Effect10Amount: "750",
      Effect11Amount: "50",
      Effect12Amount: "0.06",
      Effect13Amount: "10",
      Effect14Amount: "5",
    },
  },
  3305: {
    version: "9.20.1",
    name: "Timeworn Nomad's Medallion",
    description:
      "<stats>+10 Movement Speed<br>+50% Base Health Regen <br>+10% Cooldown Reduction<br>+2 Gold per 10 seconds</stats><br><br><unique>UNIQUE Passive - Favor:</unique> Enemy minions killed by your allies sometimes drop coins that grant <scaleMana>6%</scaleMana> missing mana (minimum 10). If there is an allied Champion nearby, sometimes the coins grant <gold>50</gold> gold instead. Cannon minions always drop coins.<hr><passive>QUEST:</passive> Earn 750 gold using this item.<br><passive>REWARD:</passive> <font color='#CFBF84'>Favor</font> is upgraded to <font color='#CFBF84'><a href='coinlinequestreward'>Emperor's Favor</a></font> and allied champions moving toward you gain 8% movement speed.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit><br><br><rules><font color='#447777'>''The medallion shines with the glory of a thousand voices when exposed to the sun.'' - Historian Shurelya, 22 June, 24 CLE</font></rules>",
    colloq: ";",
    plaintext:
      "Grants gold and mana when nearby minions die that you didn't kill",
    from: ["1006", "3304"],
    into: ["3306"],
    image: {
      full: "3305.png",
      sprite: "item2.png",
      group: "item",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 300,
      purchasable: true,
      total: 850,
      sell: 340,
    },
    tags: [
      "HealthRegen",
      "ManaRegen",
      "Active",
      "GoldPer",
      "CooldownReduction",
    ],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {},
    effect: {
      Effect1Amount: "2",
      Effect2Amount: "15",
      Effect3Amount: "50",
      Effect4Amount: "10",
      Effect5Amount: "0",
      Effect6Amount: "0",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "0",
      Effect10Amount: "750",
      Effect11Amount: "50",
      Effect12Amount: "0.06",
      Effect13Amount: "10",
      Effect14Amount: "10",
    },
    depth: 2,
  },
  3306: {
    version: "9.20.1",
    name: "Timeworn Talisman of Ascension",
    description:
      "<stats>+10 Movement Speed<br>+45 Armor<br>+175% Base Health Regen <br>+10% Cooldown Reduction<br>+2 Gold per 10 seconds</stats><br><br><unique>UNIQUE Passive - Point Runner:</unique> Builds up to +20% Movement Speed over 2 seconds while near turrets, fallen turrets and Void Gates.<br><unique>UNIQUE Passive - Favor:</unique> Enemy minions killed by your allies sometimes drop coins that grant <scaleMana>6%</scaleMana> missing mana (minimum 10). If there is an allied Champion nearby, sometimes the coins grant <gold>50</gold> gold instead. Cannon minions always drop coins.<br><active>UNIQUE Active:</active> Grants nearby allies +@Effect5Amount*100@% Movement Speed for @Effect6Amount@ seconds (60 second cooldown).<hr><passive>QUEST:</passive> Earn 750 gold using this item.<br><passive>REWARD:</passive> <font color='#CFBF84'>Favor</font> is upgraded to <font color='#CFBF84'><a href='coinlinequestreward'>Emperor's Favor</a></font> and allied champions moving toward you gain 8% movement speed.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit><br><br><rules><font color='#447777'>''Praise the sun.'' - Historian Shurelya, 22 September, 25 CLE</font></rules>",
    colloq: ";shurelya;reverie",
    plaintext:
      "Increases Health / Mana Regeneration and Cooldown Reduction. Activate to speed up nearby allies.",
    from: ["3305", "2053"],
    image: {
      full: "3306.png",
      sprite: "item2.png",
      group: "item",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 450,
      purchasable: true,
      total: 2200,
      sell: 880,
    },
    tags: [
      "HealthRegen",
      "Armor",
      "ManaRegen",
      "Active",
      "GoldPer",
      "CooldownReduction",
      "NonbootsMovement",
    ],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {
      FlatArmorMod: 45,
    },
    effect: {
      Effect1Amount: "-0.1",
      Effect2Amount: "2",
      Effect3Amount: "15",
      Effect4Amount: "25",
      Effect5Amount: "0.4",
      Effect6Amount: "3",
      Effect7Amount: "60",
      Effect8Amount: "20",
      Effect9Amount: "2",
      Effect10Amount: "750",
      Effect11Amount: "50",
      Effect12Amount: "0.06",
      Effect13Amount: "10",
      Effect14Amount: "10",
    },
    depth: 3,
  },
  3307: {
    version: "9.20.1",
    name: "Timeworn Relic Shield",
    description:
      "<stats>+50 Health<br>+2 Gold per 10 seconds </stats><br><br><unique>UNIQUE Passive - Spoils of War:</unique> Melee basic attacks execute minions below 195 (+5 per level) Health. Killing a minion heals the owner and the nearest allied champion for 5 to 30 (based on missing health) and grants them kill Gold. Healing is halved if the owner is ranged. These effects require a nearby ally. Recharges every 40 seconds. Max 2 charges.<hr><passive>QUEST:</passive> Earn 750 gold using this item and upgrade to <font color='#CFBF84'>Timeworn Targon's Brace</font>.<br><passive>REWARD:</passive> <font color='#CFBF84'>Shield Battery</font>, a permanent shield that regenerates slowly outside of combat.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";",
    plaintext:
      "Kill minions periodically to heal and grant gold to a nearby ally",
    into: ["3308"],
    image: {
      full: "3307.png",
      sprite: "item2.png",
      group: "item",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 400,
      purchasable: true,
      total: 400,
      sell: 160,
    },
    tags: ["Aura", "GoldPer", "Health", "Lane"],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 50,
    },
    effect: {
      Effect1Amount: "195",
      Effect2Amount: "5",
      Effect3Amount: "2",
      Effect4Amount: "0",
      Effect5Amount: "0",
      Effect6Amount: "0",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "2",
      Effect10Amount: "0",
      Effect11Amount: "750",
      Effect12Amount: "40",
      Effect13Amount: "2",
      Effect14Amount: "0",
      Effect15Amount: "5",
      Effect16Amount: "30",
      Effect17Amount: "0.5",
      Effect18Amount: "10",
    },
  },
  3308: {
    version: "9.20.1",
    name: "Timeworn Targon's Brace",
    description:
      "<stats>+125 Health<br>+50% Base Health Regen <br>+4 Gold per 10 seconds </stats><br><br><unique>UNIQUE Passive - Spoils of War:</unique> Melee basic attacks execute minions below 200 (+10 per level) Health. Killing a minion heals the owner and the nearest allied champion for 10 to 60 (based on missing health) and grants them kill Gold. Healing is halved if the owner is ranged. These effects require a nearby ally. Recharges every 30 seconds. Max 3 charges.<hr><passive>QUEST:</passive> Earn 750 gold using this item.<br><passive>REWARD:</passive> <font color='#CFBF84'>Shield Battery</font>, a permanent shield that regenerates slowly outside of combat.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";",
    plaintext:
      "Periodically kill enemy minions to heal and grant gold to a nearby ally",
    from: ["3307", "1006"],
    into: ["3309"],
    image: {
      full: "3308.png",
      sprite: "item2.png",
      group: "item",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 300,
      purchasable: true,
      total: 850,
      sell: 340,
    },
    tags: ["Aura", "GoldPer", "Health", "HealthRegen"],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 125,
    },
    effect: {
      Effect1Amount: "200",
      Effect2Amount: "10",
      Effect3Amount: "2",
      Effect4Amount: "0",
      Effect5Amount: "0",
      Effect6Amount: "0",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "4",
      Effect10Amount: "0",
      Effect11Amount: "750",
      Effect12Amount: "30",
      Effect13Amount: "3",
      Effect14Amount: "0",
      Effect15Amount: "10",
      Effect16Amount: "60",
      Effect17Amount: "0.5",
      Effect18Amount: "10",
    },
    depth: 2,
  },
  3309: {
    version: "9.20.1",
    name: "Timeworn Face of the Mountain",
    description:
      "<stats>+350 Health<br>+100% Base Health Regen <br>+10% Cooldown Reduction<br>+4 Gold per 10 seconds </stats><br><br><unique>UNIQUE Passive - Spoils of War:</unique> Melee basic attacks execute minions below 320 (+20 per level) Health. Killing a minion heals the owner and the nearest allied champion for 15 to 90 (based on missing health) and grants them kill Gold. Healing is halved if the owner is ranged. These effects require a nearby ally. Recharges every 20 seconds. Max 4 charges.<br><unique>UNIQUE Active:</unique> Grant a shield to you and an ally equal to 10% of your maximum Health for 4 seconds. After 4 seconds, the shields explode to slow nearby enemies by 40% for 2 seconds (60 second cooldown).  Automatically targets the most wounded ally if cast upon self.<hr><passive>QUEST:</passive> Earn 750 gold using this item.<br><passive>REWARD:</passive> <font color='#CFBF84'>Shield Battery</font>, a permanent shield that regenerates slowly outside of combat.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";",
    plaintext: "Shield an ally from damage based on your Health",
    from: ["3308", "3067"],
    image: {
      full: "3309.png",
      sprite: "item2.png",
      group: "item",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 450,
      purchasable: true,
      total: 2100,
      sell: 840,
    },
    tags: [
      "Health",
      "HealthRegen",
      "Active",
      "GoldPer",
      "CooldownReduction",
      "Slow",
    ],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 350,
    },
    effect: {
      Effect1Amount: "320",
      Effect2Amount: "15",
      Effect3Amount: "0.1",
      Effect4Amount: "4",
      Effect5Amount: "-0.4",
      Effect6Amount: "2",
      Effect7Amount: "60",
      Effect8Amount: "120",
      Effect9Amount: "4",
      Effect10Amount: "0",
      Effect11Amount: "750",
      Effect12Amount: "20",
      Effect13Amount: "4",
      Effect14Amount: "0",
      Effect15Amount: "20",
      Effect16Amount: "90",
      Effect17Amount: "0.5",
      Effect18Amount: "10",
    },
    depth: 3,
  },
  3310: {
    version: "9.20.1",
    name: "Timeworn Spellthief's Edge",
    description:
      "<stats>+10 Ability Power<br>+2 Gold per 10 seconds<br><mana>+25% Base Mana Regen </mana></stats><br><br><unique>UNIQUE Passive - Tribute:</unique> Damaging spells and attacks against champions or buildings deal 13 additional magic damage per unique spell cast. If there is a nearby ally Champion, it also grants <gold>11</gold> Gold. This can occur up to 3 times every 30 seconds. Before quest completion, killing minions and non-epic monsters slows Tribute and gold generation.<hr><passive>QUEST:</passive> Earn 750 gold using this item and upgrade to <font color='#CFBF84'>Timeworn Frostfang</font>.<br><passive>REWARD:</passive> <font color='#CFBF84'>Tribute</font> is upgraded into <font color='#CFBF84'><a href='frostqueenslinequestreward'>Queen's Tribute</a></font>.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";",
    plaintext: "Grants gold when you damage enemies",
    into: ["3311"],
    image: {
      full: "3310.png",
      sprite: "item2.png",
      group: "item",
      x: 288,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 400,
      purchasable: true,
      total: 400,
      sell: 160,
    },
    tags: ["GoldPer", "Lane", "ManaRegen", "SpellDamage"],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {
      FlatMagicDamageMod: 10,
    },
    effect: {
      Effect1Amount: "13",
      Effect2Amount: "11",
      Effect3Amount: "6",
      Effect4Amount: "3",
      Effect5Amount: "30",
      Effect6Amount: "2",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "0",
      Effect10Amount: "0",
      Effect11Amount: "0",
      Effect12Amount: "0",
      Effect13Amount: "0",
      Effect14Amount: "0",
      Effect15Amount: "0",
      Effect16Amount: "0",
      Effect17Amount: "750",
      Effect18Amount: "0.5",
      Effect19Amount: "0",
      Effect20Amount: "10",
    },
  },
  3311: {
    version: "9.20.1",
    name: "Timeworn Frostfang",
    description:
      "<stats>+20 Ability Power<br>+2 Gold per 10 seconds<br><mana>+50% Base Mana Regen </mana><br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive - Tribute:</unique> Damaging spells and attacks against champions or buildings deal 18 additional magic damage per unique spell cast. If there is a nearby ally Champion, it also grants <gold>22</gold> Gold. This can occur up to 3 times every 30 seconds. Before quest completion, killing minions and non-epic monsters slows Tribute and gold generation.<hr><passive>QUEST:</passive> Earn 750 gold using this item.<br><passive>REWARD:</passive> <font color='#CFBF84'>Tribute</font> is upgraded into <font color='#CFBF84'><a href='frostqueenslinequestreward'>Queen's Tribute</a></font>.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: ";",
    plaintext: "Grants gold when you damage an enemy",
    from: ["3310", "1004"],
    into: ["3312"],
    image: {
      full: "3311.png",
      sprite: "item2.png",
      group: "item",
      x: 336,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 325,
      purchasable: true,
      total: 850,
      sell: 340,
    },
    tags: [
      "SpellDamage",
      "ManaRegen",
      "Active",
      "GoldPer",
      "CooldownReduction",
    ],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {
      FlatMagicDamageMod: 20,
    },
    effect: {
      Effect1Amount: "18",
      Effect2Amount: "22",
      Effect3Amount: "6",
      Effect4Amount: "3",
      Effect5Amount: "30",
      Effect6Amount: "2",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "5",
      Effect10Amount: "1",
      Effect11Amount: "0",
      Effect12Amount: "0",
      Effect13Amount: "0",
      Effect14Amount: "0",
      Effect15Amount: "0",
      Effect16Amount: "0",
      Effect17Amount: "750",
      Effect18Amount: "0.5",
      Effect19Amount: "1",
      Effect20Amount: "10",
    },
    depth: 2,
  },
  3312: {
    version: "9.20.1",
    name: "Timeworn Frost Queen's Claim",
    description:
      "<stats>+60 Ability Power<br>+10% Cooldown Reduction<br>+2 Gold per 10 seconds<br><mana>+50% Base Mana Regen </mana></stats><br><br><unique>UNIQUE Passive - Tribute:</unique> Damaging spells and attacks against champions or buildings deal 18 additional magic damage per unique spell cast. If there is a nearby ally Champion, it also grants <gold>22</gold> Gold. This can occur up to 3 times every 30 seconds. Before quest completion, killing minions and non-epic monsters slows Tribute and gold generation.<br><active>UNIQUE Active:</active> Summon 2 icy ghosts for 6 seconds that seek out nearby enemy champions. Ghosts reveal enemies on contact and slow them by 40% for between 2 and 5 seconds based on how far the ghosts have traveled (90 second cooldown).<hr><passive>QUEST:</passive> Earn 750 gold using this item.<br><passive>REWARD:</passive> <font color='#CFBF84'>Tribute</font> is upgraded into <font color='#CFBF84'><a href='frostqueenslinequestreward'>Queen's Tribute</a></font>.<br><br><groupLimit>Limited to 1 Gold Income or Jungle item.</groupLimit>",
    colloq: "spooky ghosts;",
    plaintext:
      "Sends out seeking wraiths that track hidden enemies and slow them",
    from: ["3311", "1026"],
    image: {
      full: "3312.png",
      sprite: "item2.png",
      group: "item",
      x: 384,
      y: 48,
      w: 48,
      h: 48,
    },
    gold: {
      base: 500,
      purchasable: true,
      total: 2200,
      sell: 880,
    },
    tags: [
      "Active",
      "CooldownReduction",
      "GoldPer",
      "ManaRegen",
      "Slow",
      "SpellDamage",
    ],
    maps: {
      10: true,
      11: false,
      12: false,
      22: false,
    },
    stats: {
      FlatMagicDamageMod: 60,
    },
    effect: {
      Effect1Amount: "18",
      Effect2Amount: "22",
      Effect3Amount: "0",
      Effect4Amount: "3",
      Effect5Amount: "30",
      Effect6Amount: "2",
      Effect7Amount: "1",
      Effect8Amount: "2",
      Effect9Amount: "2",
      Effect10Amount: "-0.4",
      Effect11Amount: "5",
      Effect12Amount: "6",
      Effect13Amount: "50",
      Effect14Amount: "90",
      Effect15Amount: "0.25",
      Effect16Amount: "2",
      Effect17Amount: "750",
      Effect18Amount: "0.5",
      Effect19Amount: "1",
      Effect20Amount: "10",
    },
    depth: 3,
  },
  3800: {
    version: "10.20.1",
    name: "Righteous Glory",
    description:
      "<stats>+400 Health<br><mana>+300 Mana</mana><br>+30 Armor<br>+100% Base Health Regen <br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Active:</unique> Grants 75% Movement Speed when moving towards enemies or enemy turrets for 4 seconds. Once near an enemy (or after 4 seconds) a shockwave is emitted, slowing nearby enemy champion Movement Speed by 75% for 2 second(s) (90 second cooldown).",
    colloq: ";",
    plaintext:
      "Grants Health, Mana, and Armor. Activate to speed towards enemies and slow them.",
    from: ["3024", "3801"],
    image: {
      full: "3800.png",
      sprite: "item2.png",
      group: "item",
      x: 288,
      y: 96,
      w: 48,
      h: 48,
    },
    gold: {
      base: 1100,
      purchasable: true,
      total: 2650,
      sell: 1855,
    },
    tags: [
      "Health",
      "HealthRegen",
      "Armor",
      "Mana",
      "Active",
      "CooldownReduction",
      "Slow",
      "NonbootsMovement",
    ],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 400,
      FlatMPPoolMod: 300,
      FlatArmorMod: 30,
    },
    effect: {
      Effect1Amount: "0.75",
      Effect2Amount: "4",
      Effect3Amount: "-0.75",
      Effect4Amount: "2",
      Effect5Amount: "90",
      Effect6Amount: "225",
      Effect7Amount: "450",
    },
    depth: 3,
  },
  3025: {
    version: "10.20.1",
    name: "Iceborn Gauntlet",
    description:
      "<stats>+65 Armor<br>+20% Cooldown Reduction<br><mana>+500 Mana</mana></stats><br><br><unique>UNIQUE Passive - Spellblade:</unique> After using an ability, the next basic attack deals bonus physical damage equal to 100% of base Attack Damage in an area and creates an icy zone for 2 seconds that slows Movement Speed by 30% (1.5 second cooldown).<br><br>Size of zone increases with bonus armor.",
    colloq: ";frozen fist",
    plaintext: "Basic attacks create a slow field after spell cast",
    from: ["3057", "3024"],
    into: ["3387"],
    image: {
      full: "3025.png",
      sprite: "item0.png",
      group: "item",
      x: 0,
      y: 336,
      w: 48,
      h: 48,
    },
    gold: {
      base: 750,
      purchasable: true,
      total: 2700,
      sell: 1890,
    },
    tags: ["Armor", "Mana", "CooldownReduction", "Slow"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatMPPoolMod: 500,
      FlatArmorMod: 65,
    },
    effect: {
      Effect1Amount: "-0.2",
      Effect2Amount: "1",
      Effect3Amount: "2",
      Effect4Amount: "-0.3",
      Effect5Amount: "1.5",
    },
    depth: 3,
  },
  3022: {
    version: "10.20.1",
    name: "Frozen Mallet",
    description:
      "<stats>+700 Health<br>+30 Attack Damage</stats><br><br><unique>UNIQUE Passive - Icy:</unique> Basic attacks slow the target's Movement Speed for 1.5 seconds on hit (40% slow for melee attacks, 20% slow for ranged attacks).",
    colloq: ";fm",
    plaintext: "Basic attacks slow enemies",
    from: ["3052", "1011"],
    image: {
      full: "3022.png",
      sprite: "item0.png",
      group: "item",
      x: 384,
      y: 288,
      w: 48,
      h: 48,
    },
    gold: {
      base: 900,
      purchasable: true,
      total: 3100,
      sell: 2170,
    },
    tags: ["Damage", "Health", "OnHit", "Slow"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 30,
      FlatHPPoolMod: 700,
    },
    effect: {
      Effect1Amount: "1.5",
      Effect2Amount: "0.4",
      Effect3Amount: "0.2",
    },
    depth: 3,
  },
  3136: {
    version: "10.20.1",
    name: "Haunting Guise",
    description:
      "<stats>+35 Ability Power<br>+200 Health</stats><br><br><unique>UNIQUE Passive - Madness:</unique> Deal 2% more damage for each second in combat with champions (10% maximum).",
    colloq: ";mask",
    plaintext: "Increases magic damage",
    stacks: 0,
    from: ["1028", "1052"],
    into: ["3151"],
    image: {
      full: "3136.png",
      sprite: "item1.png",
      group: "item",
      x: 288,
      y: 144,
      w: 48,
      h: 48,
    },
    gold: {
      base: 665,
      purchasable: true,
      total: 1500,
      sell: 1050,
    },
    tags: ["Health", "SpellDamage"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 200,
      FlatMagicDamageMod: 35,
    },
    effect: {
      Effect1Amount: "15",
      Effect2Amount: "15",
      Effect3Amount: "1",
      Effect4Amount: "3",
      Effect5Amount: "15",
      Effect6Amount: "33",
      Effect7Amount: "2",
      Effect8Amount: "10",
      Effect9Amount: "5",
    },
    depth: 2,
  },
  3151: {
    version: "10.20.1",
    name: "Liandry's Torment",
    description:
      "<stats>+75 Ability Power<br>+300 Health</stats><br><br><unique>UNIQUE Passive - Madness:</unique> Deal 2% more damage for each second in combat with champions (10% maximum).<br><unique>UNIQUE Passive - Torment:</unique> Spells burn enemies for 3 seconds, dealing bonus magic damage equal to 1.5% of their maximum Health per second. Burn damage is increased to 2.5% against <a href='MovementImpaired'>movement-impaired</a> units.",
    colloq: ";mask",
    plaintext: "Spell damage burns enemies for a portion of their Health",
    stacks: 0,
    from: ["3136", "1026"],
    image: {
      full: "3151.png",
      sprite: "item1.png",
      group: "item",
      x: 288,
      y: 192,
      w: 48,
      h: 48,
    },
    gold: {
      base: 750,
      purchasable: true,
      total: 3100,
      sell: 2170,
    },
    tags: ["Health", "SpellDamage"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 300,
      FlatMagicDamageMod: 75,
    },
    effect: {
      Effect1Amount: "15",
      Effect2Amount: "0.015",
      Effect3Amount: "3",
      Effect4Amount: "100",
      Effect5Amount: "2",
      Effect6Amount: "10",
      Effect7Amount: "2",
      Effect8Amount: "2.5",
    },
    depth: 3,
  },
  3161: {
    version: "10.20.1",
    name: "Spear of Shojin",
    description:
      "<stats>+65 Attack Damage<br>+200 Health<br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive:</unique> <a href='FlatDamageReduction'>Reduce damage</a> from champion attacks and abilities by 10 plus 15% of bonus attack damage (maximum 300).<br><unique>UNIQUE Passive:</unique> When near at least 3 enemy champions, land a basic attack to gain <unlockedPassive>Dragon Heart</unlockedPassive> (90s cooldown).<br><br><unlockedPassive>Dragon Heart:</unlockedPassive> Block 300% more damage for 8s, refreshing on takedown.<br><br><rules></rules>",
    colloq: ";",
    plaintext:
      "Reduce damage taken from champions by a flat amount. Attack while near multiple enemy champions to increase this amount for a short time.",
    stacks: 0,
    from: ["1038", "3067"],
    image: {
      full: "3161.png",
      sprite: "item1.png",
      group: "item",
      x: 144,
      y: 240,
      w: 48,
      h: 48,
    },
    gold: {
      base: 900,
      purchasable: true,
      total: 3000,
      sell: 2100,
    },
    tags: ["Health", "Damage", "CooldownReduction"],
    maps: {
      11: false,
      12: false,
      21: true,
      22: false,
    },
    stats: {
      FlatPhysicalDamageMod: 65,
      FlatHPPoolMod: 200,
    },
    effect: {
      Effect1Amount: "300",
      Effect2Amount: "0",
      Effect3Amount: "90",
      Effect4Amount: "0",
      Effect5Amount: "10",
      Effect6Amount: "0",
      Effect7Amount: "0.3",
      Effect8Amount: "0.15",
      Effect9Amount: "8",
      Effect10Amount: "3",
    },
    depth: 3,
  },
  3285: {
    version: "10.20.1",
    name: "Luden's Echo",
    description:
      "<stats>+90 Ability Power<br><mana>+600 Mana</mana><br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive - Haste:</unique> This item gains an additional 10% Cooldown Reduction.<br><unique>UNIQUE Passive - Echo:</unique> Gain charges upon moving or casting. At 100 charges, the next damaging spell hit expends all charges to deal 100 (+10% of Ability Power) bonus magic damage to up to 4 targets on hit.",
    colloq: ";",
    plaintext: "Increases Ability Power, Mana, and Cooldown Reduction",
    from: ["3802", "1026"],
    into: ["3390"],
    image: {
      full: "3285.png",
      sprite: "item1.png",
      group: "item",
      x: 96,
      y: 336,
      w: 48,
      h: 48,
    },
    gold: {
      base: 1050,
      purchasable: true,
      total: 3200,
      sell: 2240,
    },
    tags: ["SpellDamage", "Mana", "CooldownReduction", "OnHit"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatMPPoolMod: 600,
      FlatMagicDamageMod: 90,
    },
    effect: {
      Effect1Amount: "100",
      Effect2Amount: "100",
      Effect3Amount: "4",
      Effect4Amount: "0.1",
      Effect5Amount: "35",
      Effect6Amount: "10",
      Effect7Amount: "0",
      Effect8Amount: "0",
      Effect9Amount: "-0.1",
    },
    depth: 3,
  },
  3030: {
    version: "10.20.1",
    name: "Hextech GLP-800",
    description:
      "<stats>+80 Ability Power<br><mana>+600 Mana</mana><br>+10% Cooldown Reduction</stats><br><br><unique>UNIQUE Passive - Haste:</unique> This item gains an additional 10% Cooldown Reduction.<br><unique>UNIQUE Active - Frost Bolt:</unique> Fires a spray of icy bolts that explode on first unit hit, dealing <scaleLevel>100 - 200</scaleLevel> (+20% of your Ability Power) magic damage to all enemies hit. (40 second cooldown, shared with other <font color='#9999FF'><a href='itembolt'>Hextech</a></font> items).<br><br> Enemies hit are slowed by 65% decaying over 2 second.",
    colloq: "frost cannon;",
    plaintext: "Activate to fire icy bolts to slow enemies",
    from: ["3802", "3145"],
    image: {
      full: "3030.png",
      sprite: "item0.png",
      group: "item",
      x: 240,
      y: 336,
      w: 48,
      h: 48,
    },
    gold: {
      base: 450,
      purchasable: true,
      total: 2800,
      sell: 1960,
    },
    tags: ["SpellDamage", "Mana", "Active", "CooldownReduction", "Slow"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatMPPoolMod: 600,
      FlatMagicDamageMod: 80,
    },
    effect: {
      Effect1Amount: "0",
      Effect2Amount: "0",
      Effect3Amount: "0",
      Effect4Amount: "2",
      Effect5Amount: "0.65",
      Effect6Amount: "100",
      Effect7Amount: "200",
      Effect8Amount: "0.2",
      Effect9Amount: "25",
      Effect10Amount: "0.2",
      Effect11Amount: "0.15",
      Effect12Amount: "40",
      Effect13Amount: "-0.1",
      Effect14Amount: "10",
      Effect15Amount: "-0.65",
    },
    depth: 3,
  },
  3087: {
    version: "10.20.1",
    name: "Statikk Shiv",
    description:
      "<stats>+40% Attack Speed<br>+25% Critical Strike Chance<br>+7% Movement Speed</stats><br><br><unique>UNIQUE Passive - Energized:</unique> Moving and attacking will make an attack <a href='Energized'>Energized</a>. <br><unique>UNIQUE Passive - Electroshock:</unique> Energized attacks gain <magicDamage>120 bonus magic damage</magicDamage>. Energized effects chain to 7 targets.",
    colloq: ";",
    plaintext:
      "Movement builds charges that release chain lightning on basic attack",
    from: ["3086", "2015"],
    image: {
      full: "3087.png",
      sprite: "item1.png",
      group: "item",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
    gold: {
      base: 500,
      purchasable: true,
      total: 2600,
      sell: 1820,
    },
    tags: ["AttackSpeed", "CriticalStrike", "NonbootsMovement", "OnHit"],
    maps: {
      11: true,
      12: true,
      21: true,
      22: false,
    },
    stats: {
      FlatCritChanceMod: 0.25,
      PercentMovementSpeedMod: 0.07,
      PercentAttackSpeedMod: 0.4,
    },
    effect: {
      Effect1Amount: "100",
      Effect2Amount: "80",
      Effect3Amount: "7",
      Effect4Amount: "750",
      Effect5Amount: "120",
      Effect6Amount: "120",
      Effect7Amount: "5",
    },
    depth: 3,
  },
  3027: {
    name: "Rod of Ages",
    description:
      "<stats>+300 Health<br><mana>+300 Mana</mana><br>+60 Ability Power</stats><br><br><passive>Passive:</passive> Grants +20 Health, +10 Mana, and +4 Ability Power per stack (max +200 Health, +100 Mana, and +40 Ability Power). Grants 1 stack per minute (max 10 stacks).<br><unique>UNIQUE Passive - Eternity:</unique> 15% of damage taken from champions is gained as Mana. Spending Mana restores 20% of the cost as Health, up to 25 per spell cast.",
    colloq: ";roa",
    plaintext: "Greatly increases Health, Mana, and Ability Power",
    from: ["3010", "1026"],
    image: {
      full: "3027.png",
      sprite: "item0.png",
      group: "item",
      x: 96,
      y: 336,
      w: 48,
      h: 48,
    },
    gold: {
      base: 650,
      purchasable: true,
      total: 2600,
      sell: 1820,
    },
    tags: ["Health", "HealthRegen", "Mana", "ManaRegen", "SpellDamage"],
    maps: {
      11: true,
      12: true,
      21: false,
      22: false,
    },
    stats: {
      FlatHPPoolMod: 300,
      FlatMPPoolMod: 300,
      FlatMagicDamageMod: 60,
    },
    effect: {
      Effect1Amount: "20",
      Effect2Amount: "10",
      Effect3Amount: "4",
      Effect4Amount: "1",
      Effect5Amount: "10",
      Effect6Amount: "150",
      Effect7Amount: "200",
      Effect8Amount: "8",
      Effect9Amount: "25",
      Effect10Amount: "0.2",
      Effect11Amount: "0.15",
    },
    depth: 3,
    version: "10.22.1",
  },
};
